version: '2.2'

services:

  logstash:
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    container_name: logstash
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro,Z
      - ./data:/data
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      ICD10_MAP_FILE: "/data/icd10ToSctMapClean.csv"
      KNOWLEDGE_INPUT_TO_SCT_FILE: "/data/knowledge-input-to-sct.csv"
    networks:
      - elk

networks:
  elk:
    driver: bridge
